apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-myapp

helmCharts:
  - name: myapp
    releaseName: myapp
    chartPath: ../../helm/myapp
    valuesFiles:
      - values-dev.yaml
