replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 80

rollout:
  strategy: blueGreen
  activeService: ""
  previewService: ""
  autoPromotionEnabled: true
  autoPromotionSeconds: 0
